config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  devise_for :users

   root 'shifts#index'

end

app/models/dyalisis.rb
class Dyalisis < ActiveRecord::Base
	belongs_to :user
	belongs_to :machine
	
end

app/models/machine.rb
class Machine < ActiveRecord::Base
has_many :requests
has_many :supplies,through: :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :machine
  belongs_to :supply
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :user
end

app/models/supply.rb
class Supply < ActiveRecord::Base
has_many :requests
has_many :machines, through: :requests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dyalises	
  has_many :shifts

  enum role: [:pacient, :nurse, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:type_shift, :timestamp, :end_time, :timestamp, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isabella</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% @shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_shift %><br>
    <%= f.text_field :type_shift %>
  </div>
  <div class="field">
    <%= f.label :start_shift %><br>
    <%= f.text_field :start_shift %>
  </div>
  <div class="field">
    <%= f.label :end_shift %><br>
    <%= f.text_field :end_shift %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Type shift</th>
      <th>Timestamp</th>
      <th>End time</th>
      <th>Timestamp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.type_shift %></td>
        <td><%= shift.timestamp %></td>
        <td><%= shift.end_time %></td>
        <td><%= shift.timestamp %></td>
        <td><%= shift.user %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type shift:</strong>
  <%= @shift.type_shift %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @shift.timestamp %>
</p>

<p>
  <strong>End time:</strong>
  <%= @shift.end_time %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @shift.timestamp %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift.user %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>